export const transData = [
  {
    id: 1,
    ref: 4947,
    bill: "Enterprize Year Subscription",
    issue: "10-05-2019",
    due: "10-13-2019",
    total: "599.00",
    status: "Due",
  },
  {
    id: 2,
    ref: 4904,
    bill: "Maintenance Year Subscription",
    issue: "06-19-2019",
    due: "06-26-2019",
    total: "99.00",
    status: "Paid",
  },
  {
    id: 3,
    ref: 4829,
    bill: "Enterprize Year Subscription",
    issue: "10-04-2018",
    due: "10-12-2018",
    total: "599.00",
    status: "Paid",
  },
  {
    id: 4,
    ref: 4830,
    bill: "Enterprize Anniversary Subscription",
    issue: "12-04-2018",
    due: "14-12-2018",
    total: "399.00",
    status: "Paid",
  },
  {
    id: 5,
    ref: 4840,
    bill: "Enterprize Coverage Subscription",
    issue: "12-08-2018",
    due: "13-22-2018",
    total: "99.00",
    status: "Cancelled",
  },
  {
    id: 6,
    ref: 4844,
    bill: "	Manual Subscription Adjustments",
    issue: "12-08-2018",
    due: "13-22-2018",
    total: "99.00",
    status: "Paid",
  },
  {
    id: 7,
    ref: 4847,
    bill: "Automatic Subscription Adjustments",
    issue: "12-08-2018",
    due: "13-22-2018",
    total: "99.00",
    status: "Paid",
  },
  {
    id: 8,
    ref: 4848,
    bill: "Tiered Subscription",
    issue: "12-08-2018",
    due: "13-22-2018",
    total: "99.00",
    status: "Paid",
  },
  {
    id: 9,
    ref: 4849,
    bill: "Tiered Subscription",
    issue: "12-08-2018",
    due: "13-22-2018",
    total: "99.00",
    status: "Paid",
  },
  {
    id: 10,
    ref: 4750,
    bill: "Flexible Subscription Plan",
    issue: "12-08-2018",
    due: "13-22-2018",
    total: "99.00",
    status: "Paid",
  },
  {
    id: 11,
    ref: 4510,
    bill: "Enterprize Year Subscription",
    issue: "10-05-2019",
    due: "10-13-2019",
    total: "599.00",
    status: "Due",
  },
  {
    id: 12,
    ref: 4520,
    bill: "Maintenance Year Subscription",
    issue: "06-19-2019",
    due: "06-26-2019",
    total: "99.00",
    status: "Paid",
  },
  {
    id: 13,
    ref: 4530,
    bill: "Enterprize Year Subscription",
    issue: "10-04-2018",
    due: "10-12-2018",
    total: "599.00",
    status: "Paid",
  },
  {
    id: 14,
    ref: 4560,
    bill: "Enterprize Anniversary Subscription",
    issue: "12-04-2018",
    due: "14-12-2018",
    total: "399.00",
    status: "Paid",
  },
  {
    id: 15,
    ref: 4570,
    bill: "Enterprize Coverage Subscription",
    issue: "12-08-2018",
    due: "13-22-2018",
    total: "99.00",
    status: "Cancelled",
  },
  {
    id: 16,
    ref: 4580,
    bill: "	Manual Subscription Adjustments",
    issue: "12-08-2018",
    due: "13-22-2018",
    total: "99.00",
    status: "Paid",
  },
  {
    id: 17,
    ref: 4590,
    bill: "Automatic Subscription Adjustments",
    issue: "12-08-2018",
    due: "13-22-2018",
    total: "99.00",
    status: "Paid",
  },
  {
    id: 18,
    ref: 4600,
    bill: "Tiered Subscription",
    issue: "12-08-2018",
    due: "13-22-2018",
    total: "99.00",
    status: "Paid",
  },
  {
    id: 19,
    ref: 4425,
    bill: "Tiered Subscription",
    issue: "12-08-2018",
    due: "13-22-2018",
    total: "99.00",
    status: "Paid",
  },
  {
    id: 20,
    ref: 4490,
    bill: "Flexible Subscription Plan",
    issue: "12-08-2018",
    due: "13-22-2018",
    total: "99.00",
    status: "Paid",
  },
];

export const orderData = [
  {
    id: 1,
    title: "Thanh toán đã nhận",
    company: "Công ty ABC",
    contact: {
      phone: "0909 123 456",
      email: "ke.toan@gmail.com",
    },
    paymentMethod: "Chuyển khoản ngân hàng",
    transactionRef: "KYC001",
    amount: "5.000.000",
    kyc: "50",
    status: "Completed",
  },
  {
    id: 2,
    title: "Thanh toán đã nhận",
    company: "Công ty ABC",
    contact: {
      phone: "0909 123 456",
      email: "ke.toan@gmail.com",
    },
    paymentMethod: "Ví điện tử",
    transactionRef: "KYC001",
    amount: "3.000.000",
    kyc: "30",
    status: "Upcoming",
  },
  {
    id: 3,
    title: "Yêu cầu hoàn tiền",
    company: "Công ty ABC",
    contact: {
      phone: "0909 123 456",
      email: "ke.toan@gmail.com",
    },
    paymentMethod: "Thẻ Visa/Master",
    transactionRef: "KYC001",
    amount: "5.000.000",
    kyc: "50",
    status: "Rejected",
  },
  {
    id: 4,
    title: "Ghi nhận lượt sử dụng",
    company: "Công ty ABC",
    contact: {
      phone: "0909 123 456",
      email: "ke.toan@gmail.com",
    },
    paymentMethod: "Chuyển khoản",
    transactionRef: "KYC001",
    amount: "5.000.000",
    kyc: "50",
    status: "Pending",
  },
  {
    id: 1,
    title: "Thanh toán đã nhận",
    company: "Công ty ABC",
    contact: {
      phone: "0909 123 456",
      email: "ke.toan@gmail.com",
    },
    paymentMethod: "Chuyển khoản ngân hàng",
    transactionRef: "KYC001",
    amount: "5.000.000",
    kyc: "50",
    status: "Completed",
  },
  {
    id: 2,
    title: "Thanh toán đã nhận",
    company: "Công ty ABC",
    contact: {
      phone: "0909 123 456",
      email: "ke.toan@gmail.com",
    },
    paymentMethod: "Ví điện tử",
    transactionRef: "KYC001",
    amount: "3.000.000",
    kyc: "30",
    status: "Upcoming",
  },
  {
    id: 3,
    title: "Yêu cầu hoàn tiền",
    company: "Công ty ABC",
    contact: {
      phone: "0909 123 456",
      email: "ke.toan@gmail.com",
    },
    paymentMethod: "Thẻ Visa/Master",
    transactionRef: "KYC001",
    amount: "5.000.000",
    kyc: "50",
    status: "Rejected",
  },
  {
    id: 4,
    title: "Ghi nhận lượt sử dụng",
    company: "Công ty ABC",
    contact: {
      phone: "0909 123 456",
      email: "ke.toan@gmail.com",
    },
    paymentMethod: "Chuyển khoản",
    transactionRef: "KYC001",
    amount: "5.000.000",
    kyc: "50",
    status: "Pending",
  },
  {
    id: 1,
    title: "Thanh toán đã nhận",
    company: "Công ty ABC",
    contact: {
      phone: "0909 123 456",
      email: "ke.toan@gmail.com",
    },
    paymentMethod: "Chuyển khoản ngân hàng",
    transactionRef: "KYC001",
    amount: "5.000.000",
    kyc: "50",
    status: "Completed",
  },
  {
    id: 2,
    title: "Thanh toán đã nhận",
    company: "Công ty ABC",
    contact: {
      phone: "0909 123 456",
      email: "ke.toan@gmail.com",
    },
    paymentMethod: "Ví điện tử",
    transactionRef: "KYC001",
    amount: "3.000.000",
    kyc: "30",
    status: "Upcoming",
  },
  {
    id: 3,
    title: "Yêu cầu hoàn tiền",
    company: "Công ty ABC",
    contact: {
      phone: "0909 123 456",
      email: "ke.toan@gmail.com",
    },
    paymentMethod: "Thẻ Visa/Master",
    transactionRef: "KYC001",
    amount: "5.000.000",
    kyc: "50",
    status: "Rejected",
  },
  {
    id: 4,
    title: "Ghi nhận lượt sử dụng",
    company: "Công ty ABC",
    contact: {
      phone: "0909 123 456",
      email: "ke.toan@gmail.com",
    },
    paymentMethod: "Chuyển khoản",
    transactionRef: "KYC001",
    amount: "5.000.000",
    kyc: "50",
    status: "Pending",
  },
  {
    id: 1,
    title: "Thanh toán đã nhận",
    company: "Công ty ABC",
    contact: {
      phone: "0909 123 456",
      email: "ke.toan@gmail.com",
    },
    paymentMethod: "Chuyển khoản ngân hàng",
    transactionRef: "KYC001",
    amount: "5.000.000",
    kyc: "50",
    status: "Completed",
  },
  {
    id: 2,
    title: "Thanh toán đã nhận",
    company: "Công ty ABC",
    contact: {
      phone: "0909 123 456",
      email: "ke.toan@gmail.com",
    },
    paymentMethod: "Ví điện tử",
    transactionRef: "KYC001",
    amount: "3.000.000",
    kyc: "30",
    status: "Upcoming",
  },
  {
    id: 3,
    title: "Yêu cầu hoàn tiền",
    company: "Công ty ABC",
    contact: {
      phone: "0909 123 456",
      email: "ke.toan@gmail.com",
    },
    paymentMethod: "Thẻ Visa/Master",
    transactionRef: "KYC001",
    amount: "5.000.000",
    kyc: "50",
    status: "Rejected",
  },
  {
    id: 4,
    title: "Ghi nhận lượt sử dụng",
    company: "Công ty ABC",
    contact: {
      phone: "0909 123 456",
      email: "ke.toan@gmail.com",
    },
    paymentMethod: "Chuyển khoản",
    transactionRef: "KYC001",
    amount: "5.000.000",
    kyc: "50",
    status: "Pending",
  },
];

export const statusOptions = [
  { value: "Paid", label: "Paid" },
  { value: "Due", label: "Due" },
  { value: "Canceled", label: "Cancelled" },
];

export const cryptoActivityOptions = [
  { value: "Deposit", label: "Deposit" },
  { value: "Buy", label: "Buy Coin" },
  { value: "Sell", label: "Sell Coin" },
  { value: "Transfer", label: "Transfer" },
  { value: "Withdraw", label: "Withdraw" },
];

export const filterStatusOptions = [
  { value: "Pending", label: "Pending" },
  { value: "Rejected", label: "Rejected" },
  { value: "Upcoming", label: "Upcoming" },
  { value: "Completed", label: "Completed" },
];

export const filterCoin = [
  { value: "Bitcoin", label: "Bitcoin" },
  { value: "Etherium", label: "Etherium" },
  { value: "Litecoin", label: "Litecoin" },
];

export const filterPaymentmethod = [
  { value: "Paypal", label: "Paypal" },
  { value: "Bank", label: "Bank" },
];
